[package]
name = "ryu-rust-example"
version = "0.1.0"
edition = "2021"

[dependencies]
ryu = { path = "../../tools/rust_api" }
arrow = { version = "55", optional = true, default-features = false, features = [] }

[features]
arrow = ["ryu/arrow", "dep:arrow"]
