name: Build Linux Wheels

on:
  workflow_dispatch:
    inputs:
      isNightly:
        description: "Whether the build is a nightly build?"
        type: boolean
        required: true
        default: false
      isDeploy:
        description: "Deploy to PyPI? (if false, deploys to test PyPI)"
        type: boolean
        required: true
        default: false
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-linux-wheels-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          pip3 install -U pip setuptools wheel

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          python3 -m pip install --break-system-packages packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Create source distribution
        working-directory: ./scripts/pip-package/
        run: |
          rm -rf wheelhouse ryugraph.tar.gz
          mkdir wheelhouse
          python3 package_tar.py ryugraph.tar.gz

      - name: Build wheels for Linux x86_64
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_SKIP: pp* cp36* cp37*
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BUILD_VERBOSITY: 3
        with:
          package-dir: ./scripts/pip-package/ryugraph.tar.gz
          output-dir: ./scripts/pip-package/wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: linux-wheels-x86_64
          path: ./scripts/pip-package/wheelhouse/*.whl

  build-linux-wheels-aarch64:
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          pip3 install -U pip setuptools wheel

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Create source distribution
        working-directory: ./scripts/pip-package/
        run: |
          rm -rf wheelhouse ryugraph.tar.gz
          mkdir wheelhouse
          python3 package_tar.py ryugraph.tar.gz

      - name: Build wheels for Linux aarch64
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_SKIP: pp* cp36* cp37*
          CIBW_ARCHS_LINUX: aarch64
          CIBW_BUILD_VERBOSITY: 3
        with:
          package-dir: ./scripts/pip-package/ryugraph.tar.gz
          output-dir: ./scripts/pip-package/wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: linux-wheels-aarch64
          path: ./scripts/pip-package/wheelhouse/*.whl

  deploy-linux-wheels:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: [build-linux-wheels-x86_64, build-linux-wheels-aarch64]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-wheels-x86_64
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: linux-wheels-aarch64
          path: dist

      - name: List wheels
        run: ls -lh dist/

      - name: Deploy to PyPI test
        if: ${{ inputs.isDeploy != true }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          skip-existing: true

      - name: Deploy to PyPI
        if: ${{ inputs.isDeploy == true }}
        uses: pypa/gh-action-pypi-publish@release/v1
