name: Build Linux Node.js Module

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-linux-nodejs-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          /opt/python/cp310-cp310/bin/python -m pip install packaging
          /opt/python/cp310-cp310/bin/python update-nightly-build-version.py
        working-directory: scripts
      
      - name: Create Node.js source distribution
        working-directory: tools/nodejs_api
        run: |
          rm -rf ryu-source.tar.gz package *.node
          node package

      - name: Extract tarball
        working-directory: tools/nodejs_api
        run: tar -xvzf ryu-source.tar.gz

      - name: Build Node.js native module
        working-directory: tools/nodejs_api/package
        run: |
          npm i

      - name: Move Node.js native module
        working-directory: tools/nodejs_api/package
        run: mv ryujs.node ryujs-linux-x64.node

      - uses: actions/upload-artifact@v4
        with:
          name: linux-nodejs-module-x86_64
          path: tools/nodejs_api/package/ryujs-linux-x64.node

  build-linux-nodejs-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          /opt/python/cp310-cp310/bin/python -m pip install packaging
          /opt/python/cp310-cp310/bin/python update-nightly-build-version.py
        working-directory: scripts

      - name: Create Node.js source distribution
        working-directory: tools/nodejs_api
        run: |
          rm -rf ryu-source.tar.gz package *.node
          node package

      - name: Extract tarball
        working-directory: tools/nodejs_api
        run: tar -xvzf ryu-source.tar.gz

      - name: Build Node.js native module
        working-directory: tools/nodejs_api/package
        run: npm i

      - name: Move Node.js native module
        working-directory: tools/nodejs_api/package
        run: mv ryujs.node ryujs-linux-arm64.node

      - uses: actions/upload-artifact@v4
        with:
          name: linux-nodejs-module-aarch64
          path: tools/nodejs_api/package/ryujs-linux-arm64.node
