name: Build Linux Wheels

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-linux-wheels-x86_64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y patchelf
          python3 -m pip install --break-system-packages -U pip setuptools wheel auditwheel

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          python3 -m pip install --break-system-packages packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Create source distribution
        working-directory: ./scripts/pip-package/
        run: |
          rm -rf wheelhouse ryugraph.tar.gz
          mkdir wheelhouse
          python3 package_tar.py ryugraph.tar.gz

      - name: Build wheels for Linux x86_64
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_SKIP: pp*
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BUILD_VERBOSITY: 3
        with:
          package-dir: ./scripts/pip-package/ryugraph.tar.gz
          output-dir: ./scripts/pip-package/wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: linux-wheels-x86_64
          path: ./scripts/pip-package/wheelhouse/*.whl

  build-linux-wheels-aarch64:
    # Make sure this job runs on the larger self-hosted Linux ARM64 machine
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y patchelf
          python3 -m pip install --break-system-packages -U pip setuptools wheel auditwheel

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          python3 -m pip install --break-system-packages packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Create source distribution
        working-directory: ./scripts/pip-package/
        run: |
          python3 package_tar.py ryugraph.tar.gz

      - name: Build wheels for Linux aarch64
        uses: pypa/cibuildwheel@v2.22
        env:
          CIBW_SKIP: pp*
          CIBW_ARCHS_LINUX: aarch64
          CIBW_BUILD_VERBOSITY: 3
        with:
          package-dir: ./scripts/pip-package/ryugraph.tar.gz
          output-dir: ./scripts/pip-package/wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: linux-wheels-aarch64
          path: ./scripts/pip-package/wheelhouse/*.whl
