name: Build Mac Precompiled Binaries

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1

jobs:
  build-precompiled-bin-universal:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: scripts

      - name: Build universal precompiled binaries
        run: |
          make NUM_THREADS=$(sysctl -n hw.ncpu)
          make install
        env:
          MACOSX_DEPLOYMENT_TARGET: 11.0
          CMAKE_OSX_ARCHITECTURES: "x86_64;arm64"

      - name: Collect artifacts
        run: |
          mv install/include/ryu.h .
          mv install/include/ryu.hpp .
          mv install/lib/libryu.dylib .
          mv install/bin/ryu .

      - name: Verify binary information
        run: |
          file -b ryu
          otool -l ryu | grep minos
          file -b libryu.dylib
          otool -l libryu.dylib | grep minos

      - name: Create tarball
        run: |
          tar -czvf libryu-osx-universal.tar.gz ryu.h ryu.hpp libryu.dylib
          tar -czvf ryu_cli-osx-universal.tar.gz ryu

      - uses: actions/upload-artifact@v4
        with:
          name: libryu-osx-universal
          path: libryu-osx-universal.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: ryu_cli-osx-universal
          path: ryu_cli-osx-universal.tar.gz
